bets = {
    "Grzegorz": {
        "Walia-Iran": [2, 0, 0],
        "Katar-Senegal": [2, 0, 0],
        "Holandia-Ekwador": [2, 0, 0],
        "Anglia-USA": [2, 0, 0],
        "Tunezja-Australia": [2, 9, 0],
        "Polska-Arabia Saudyjska": [9, 0, 0],
        "Francja-Dania": [2, 9, 0],
        "Argentyna-Meksyk": [2, 9, 0],
    },
    "Mariusz": {
        "Walia-Iran": [8, 2, 0],
        "Katar-Senegal": [8, 0, 0],
        "Holandia-Ekwador": [2, 8, 0],
        "Anglia-USA": [2, 8, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 0, 0],
        "Argentyna-Meksyk": [2, 0, 0],
    },
    "Natalia": {
        "Walia-Iran": [0, 2, 0],
        "Katar-Senegal": [2, 8, 0],
        "Holandia-Ekwador": [2, 8, 0],
        "Anglia-USA": [2, 3, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 0, 0],
        "Argentyna-Meksyk": [2, 0, 0],
    },
    "Michał K.": {
        "Walia-Iran": [2, 2, 0],
        "Katar-Senegal": [2, 0, 0],
        "Holandia-Ekwador": [2, 1, 0],
        "Anglia-USA": [2, 2, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 1, 0],
        "Argentyna-Meksyk": [2, 2, 0],
    },
    "Michał J.": {
        "Walia-Iran": [6, 2, 0],
        "Katar-Senegal": [2, 0, 0],
        "Holandia-Ekwador": [2, 5, 0],
        "Anglia-USA": [2, 0, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 5, 0],
        "Argentyna-Meksyk": [2, 0, 0],
    },
    "Wojtek": {
        "Walia-Iran": [4, 2, 0],
        "Katar-Senegal": [2, 3, 0],
        "Holandia-Ekwador": [2, 0, 0],
        "Anglia-USA": [2, 2, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 4, 0],
        "Argentyna-Meksyk": [2, 0, 0],
    },
    "Mateusz": {
        "Walia-Iran": [1, 2, 0],
        "Katar-Senegal": [2, 0, 0],
        "Holandia-Ekwador": [2, 1, 0],
        "Anglia-USA": [2, 4, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 1, 0],
        "Argentyna-Meksyk": [2, 0, 0],
    },
    "Krzysztof P.": {
        "Walia-Iran": [0, 2, 0],
        "Katar-Senegal": [2, 0, 0],
        "Holandia-Ekwador": [2, 4, 0],
        "Anglia-USA": [2, 4, 0],
        "Tunezja-Australia": [2, 4, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 4, 0],
        "Argentyna-Meksyk": [2, 0, 0],
    },
    "Krzysztof W.": {
        "Walia-Iran": [2, 2, 0],
        "Katar-Senegal": [2, 2, 0],
        "Holandia-Ekwador": [2, 2, 0],
        "Anglia-USA": [2, 3, 0],
        "Tunezja-Australia": [2, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 1, 0],
        "Argentyna-Meksyk": [2, 1, 0],
    },
    "Wiktor": {
        "Walia-Iran": [0, 3, 0],
        "Katar-Senegal": [2, 3, 0],
        "Holandia-Ekwador": [3, 0, 0],
        "Anglia-USA": [3, 0, 0],
        "Tunezja-Australia": [3, 0, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 3, 0],
        "Argentyna-Meksyk": [2, 3, 0],
    },
    "Łukasz": {
        "Walia-Iran": [0, 2, 0],
        "Katar-Senegal": [2, 3, 0],
        "Holandia-Ekwador": [2, 2, 0],
        "Anglia-USA": [2, 4, 0],
        "Tunezja-Australia": [2, 4, 0],
        "Polska-Arabia Saudyjska": [2, 0, 0],
        "Francja-Dania": [2, 4, 0],
        "Argentyna-Meksyk": [2, 4, 0],
    }
}
